### ISSUE TITLE
通过WordPress RestAPI上传图片后，图片没有存储到OSS里面，而是存储到了本地。

### ISSUE THREAD

**Issue by mosserlee** [IvanChou/aliyun-oss-support#105]
备注：

1. OSS配置正确，WordPress 网站上传图片没问题。
2. 通过WordPress REST API 上传图片后，图片被错误地保存到了本地，而非OSS里面，导致不能显示。
3. 暂时不能确定，这是WP的bug，还是本插件的bug。

谢谢

**Comment by anccd** [comment]
哈哈 我用的是新版的wp ，上传的图片阿里云里有本地同样也有，那么问题来了，部分链接图片地址（小尺寸图）是本地的，部分的是阿里云的，阿里云的链接图片正常本地的就挂了

**Comment by mosserlee** [comment]
> 哈哈 我用的是新版的wp ，上传的图片阿里云里有本地同样也有，那么问题来了，部分链接图片地址（小尺寸图）是本地的，部分的是阿里云的，阿里云的链接图片正常本地的就挂了

您说的这个问题，按照插件原作者的推荐，启用OSS的图片服务后，并勾选【不在本地服务器上保留文件】选项，这样就完全切换到阿里云OSS了，不会出现部分本地，部分云上的问题。理论上，这是最优雅的配置。

我的问题是使用了WP的RestAPI 上传后，图片被上传到了本地。这是两个问题。

**Comment by inoodle-Git** [comment]
> > 哈哈 我用的是新版的wp ，上传的图片阿里云里有本地同样也有，那么问题来了，部分链接图片地址（小尺寸图）是本地的，部分的是阿里云的，阿里云的链接图片正常本地的就挂了
> 
> 您说的这个问题，按照插件原作者的推荐，启用OSS的图片服务后，并勾选【不在本地服务器上保留文件】选项，这样就完全切换到阿里云OSS了，不会出现部分本地，部分云上的问题。理论上，这是最优雅的配置。
> 
> 我的问题是使用了WP的RestAPI 上传后，图片被上传到了本地。这是两个问题。

看起来像是api的优先级的问题，会不会rest api比oss插件的上传动作更早？
