### ISSUE TITLE
bucket设置成私有，如何对url添加鉴权签名

### ISSUE THREAD

**Issue by creatint** [IvanChou/aliyun-oss-support#109]
选项中没有看到开启鉴权的按钮

**Comment by inoodle-Git** [comment]
我添加了一部分代码，可以实现鉴权，但因为WordPress古腾堡编辑器的问题，编辑器界面默认加载的是数据库不带鉴权的图片链接且无法修改，word有个content_edit_pre()函数可以在编辑器加载内容时对图片链接进行修改，但是它在古腾堡中不生效，只有官方修复这个bug，鉴权才能完美运行。

**Comment by inoodle-Git** [comment]
3.2.7已经添加URL鉴权功能，并解决古藤堡编辑器加载时添加鉴权和兼容性问题。[点这里下载最新版](https://github.com/IvanChou/aliyun-oss-support/releases) 
已测试通过，如有bug请反馈。
