### ISSUE TITLE
开启图片服务之后还是上传缩略图

### ISSUE THREAD

**Issue by vicguo0724** [IvanChou/aliyun-oss-support#118]
图片服务开启之后还是上传了缩略图，请问一下这个是怎么回事呀
插件版本3.2.7，wordpress版本5.2

**Comment by luyu99998888** [comment]
当前版本确实存在这个问题，希望作者尽快修复

**Comment by IvanChou** [comment]
https://github.com/IvanChou/aliyun-oss-support/releases

3.3.0 中已修复这个问题
