### ISSUE TITLE
有严重的BUG，启动图片服务还是上传缩略图到阿里云上

### ISSUE THREAD

**Issue by leadroy** [IvanChou/aliyun-oss-support#120]
根据功能：需要注意的是，启用『图片服务』之后，插件不再会上传 WordPress 生成的缩略图到 OSS 中，但是服务器上依旧有保留各尺寸的缩略图

问题：
1:启动[图片服务]，还是上传略缩图到阿里服务器上。
2:既然定义了阿里OSS图片样式，为什么还要在本地生成这么多各种尺寸的图片？本地生成这些图片还不能关闭。
3.清理服务器存储这个功能是多久在本地服务器上清单的？不知道触发的时机。

**Comment by sarkrui** [comment]
同意，我也有同样的问题！使用的是最新版本

**Comment by sarkrui** [comment]
可能是为了避免关闭 Aliyun OSS 导致本地服务器缩略图丢失的情况

**Comment by luyu99998888** [comment]
当前版本确实存在这个问题，希望作者尽快修复

**Comment by IvanChou** [comment]
Wordpress 附件机制升级了？

**Comment by IvanChou** [comment]
https://github.com/IvanChou/aliyun-oss-support/releases

Wordpress  的图片处理机制真的有变更，3.3.0 中已修复
