### ISSUE TITLE
编辑图片之后不会自动上传至 OSS

### ISSUE THREAD

**Issue by 0xJacky** [IvanChou/aliyun-oss-support#13]
如题

**Comment by IvanChou** [comment]
这个确实还没有，空了会更新一下

**Comment by 0xJacky** [comment]
更新了之后上传附件会出现 HTTP 错误

**Comment by IvanChou** [comment]
我重新打包了 你下个最新的试试
配置要检查后重新保存一次
https://github.com/IvanChou/aliyun-oss-support/releases

**Comment by 0xJacky** [comment]
好的 我晚上试试

**Comment by 0xJacky** [comment]
然而还是 HTTP 错误，走的内网杭州OSS

**Comment by IvanChou** [comment]
我还没有测过内网 晚上回去试一下

**Comment by IvanChou** [comment]
我内网测试了一下，没有复现出问题
你试试在机器上 `ping oss-cn-hangzhou-internal.aliyuncs.com`
或者  `nc -v oss-cn-hangzhou-internal.aliyuncs.com 80` 看看通不通 

如果你之前装过 2.x 版本，可以卸载一次，彻底清掉旧的配置，再重新安装并配置

还不行的话，就需要请你自己试着找下 bug 了

**Comment by 0xJacky** [comment]
已经发现问题所在了，如果储存路径留空或者为 / （保存到根目录）就会导致出错

**Comment by 0xJacky** [comment]
beta2可以正常使用了~
