### ISSUE TITLE
原图怎么加水印？

### ISSUE THREAD

**Issue by fxd2006** [IvanChou/aliyun-oss-support#15]
请教一下，怎么给存在OSS的原图加水印呢？我加了4个OSS样式（medium，large，post-thumbnail，thumbnail） ,后台媒体里看到缩略图都是有水印的，但原图没有水印，原图要怎么加水印呢？原图的样式叫什么呢？

**Comment by IvanChou** [comment]
水印的问题我还没有注意过

你设置了 OSS样式（medium，large，post-thumbnail，thumbnail）， 应该是下到老版了
2.4.0 开始，为了增加对 srcset 的支持，已经不需要设置这个了，会根据 WP 的需要自动处理图片尺寸 😂

原图没有水印是不是是因为 Image Service 没有对图片进行处理，所以连水印都没有打？ 我去确认一下

PS: 明后两天可能会发一个改动挺大的新版本

**Comment by IvanChou** [comment]
发现了 我的文章没有更新。。。。。我的错

**Comment by IvanChou** [comment]
看了一下阿里云的图片服务
水印功能设计得略微复杂，无法通过直接给参数的方式实现，只有通过预设图片服务的样式来实现
因为之前没有考虑到水印的问题，所以原图没有给样式的参数，于是就出现了你的原图没有水印问题

2.4.0 开始，为了支持 srcset 我甚至已经移除了 预设样式这个方式 run~cry~~

明天发的新版里我会修复这个问题，提供两种方式的支持

**Comment by IvanChou** [comment]
请使用这个版本 
https://github.com/IvanChou/aliyun-oss-support/releases/tag/3.0.0-beta

相应的 你还需要添加两个预设样式 origin 和 medium_large
origin 就是加水印的原图
medium_large 是 wordpress 的一个新的样式，后台还没有对应设置，主要是为了支持 srcset 的
