### ISSUE TITLE
建议不要打包aliyun-oss-wp

### ISSUE THREAD

**Issue by Isongw** [IvanChou/aliyun-oss-support#16]
3.0beta里面，aliyun-oss-wp.phar不利于修改，建议还是不要打包了，比如我现在就想修改一下图片服务的参数，默认的 20w_30h_1l_1c 不是太适合我

**Comment by IvanChou** [comment]
嗯 这个是可选的，需要打包的版本可以直接下载源码的 zip 包

https://github.com/IvanChou/aliyun-oss-support/archive/master.zip

下载后，也许需要改下文件名就好了

**Comment by IvanChou** [comment]
突然发现之前的图片规则确实有问题，不应该是 `_1l_1c` 而是 `_1e_1l_1c`, 至于 `20w_30h` 是从 WordPress 中取得宽和高

如果你依旧需要自定义图片处理规则，修改源码并不是一个推荐的方式，你可以试一试使用 图片预设样式 这个功能

参见：
https://github.com/IvanChou/aliyun-oss-support/wiki/How-to-use-Image-Service#%E5%9B%BE%E7%89%87%E5%A4%84%E7%90%86%E9%A2%84%E8%AE%BE%E6%A0%B7%E5%BC%8F
