### ISSUE TITLE
无法启用插件

### ISSUE THREAD

**Issue by fxd2006** [IvanChou/aliyun-oss-support#17]
我使用阿里云的弹性WEB托管，不能启用插件，错误如下：

无法启用插件，因为它引起了一个致命错误（fatal error）。
ERROR: manifest length read was "389051" should be "7602176"

不知道是为什么

**Comment by IvanChou** [comment]
php 版本是多少？ 是否低于 5.3

阿里云官方的 [aliyun-oss-php-sdk](https://github.com/aliyun/aliyun-oss-php-sdk) 要求 PHP 5.3+

**Comment by fxd2006** [comment]
PHP版本 5.5.30

**Comment by fxd2006** [comment]
切换到5.4 5.3版本也是一样报错误。

**Comment by IvanChou** [comment]
有空我去找个 弹性WEB托管 试一下

**Comment by IvanChou** [comment]
弹性 web 托管这么贵啊~~ 测试不起了

按网上查到的信息这个问题应该是 phar 打包导致的，你可以试试没有打包的版本
[3.0.2](https://github.com/IvanChou/aliyun-oss-support/releases/latest) 中下载 `Source code (zip)`， 依旧不行的话，那就是 阿里自己家的 SDK phar 不支持自己家的产品了  😂
