### ISSUE TITLE
上传图片会报HTTP错误，但图片能上传成功，可最终图片尺寸会丢失

### ISSUE THREAD

**Issue by MRchenkuan** [IvanChou/aliyun-oss-support#18]
错误信息如下

Warning: filesize():
stat failed for /data/home/bxu2359040325/htdocs/wp-content/uploads/2016/10/72P3CLWTL9S@SVBF-150x150.png in phar:///data/home/bxu2359040325/htdocs/wp-content/plugins/aliyun-oss-support-master/aliyun-oss-php-sdk-2.0.7.phar/src/OSS/OssClient.php on line 1310

Fatal error: Uncaught exception 'OSS\Core\OssException' with message 'The size of `fileUpload` cannot be determined in multiuploadFile().' in phar:///data/home/bxu2359040325/htdocs/wp-content/plugins/aliyun-oss-support-master/aliyun-oss-php-sdk-2.0.7.phar/src/OSS/OssClient.php:1317 Stack trace: 
#0 /data/home/bxu2359040325/htdocs/wp-content/plugins/aliyun-oss-support-master/src/Upload.php(61): OSS\OssClient->multiuploadFile('bucket-3', 'wp-content/uplo...', '/data/home/bxu2...', Array)
#1 [internal function]: OSS\WP\Upload->uploadThumbToOss(Array)
#2 /data/home/bxu2359040325/htdocs/wp-includes/plugin.php(235): call_user_func_array(Array, Array)
#3 /data/home/bxu2359040325/htdocs/wp-includes/post.php(4891): apply_filters('wp_update_attac...', Array, 153)
#4 /data/home/bxu2359040325/htdocs/wp-admin/includes/media.php(375): wp_update_attachment_metadata(153, Array)
#5 /data/home/bxu2359040325/htdocs/wp-admin/async-upload.php(93): media_handle_upload('async-upload', 0)
#6 {main} thrown in phar:///data/home/bxu2359040325/htdocs/wp-content/plugins/aliyun-oss-support-master/aliyun-oss-php-sdk-2.0.7.phar/src/OSS/OssClient.php on line 1317

**Comment by MRchenkuan** [comment]
接下来，文章中引用到的图片能展示
作为缩略图不能展示
作为文章特色图不能展示

查看页面元素后，发现图片样式定义均为1px *1px

**Comment by MRchenkuan** [comment]
另外，若取消勾选“不在本地服务器上保留文件”，则一切恢复正常，所以推断：
在本地服务器上未保留文件时，WordPress无法获取图片尺寸，会直接报错，望修复

**Comment by IvanChou** [comment]
以前也有遇到这个问题，应该是我的锅，今明两天会处理

**Comment by IvanChou** [comment]
处理的时候，我发现这是相当严重的 BUG 啊，😄 😄  。。。原因是我在增加 编辑图片保存到 OSS 这个功能的时候，选用的 Hook 在上传图片的时候也会执行，从而导致了上传图片的时候缩略图会被上传到 OSS 两次。

还好有本地不保留文件这个选项，第一次上传完后把文件删了，于是第二次上传就报错了，否则都不知道什么时候才能抓到它。

帮我试试新版本 [3.0.2](https://github.com/IvanChou/aliyun-oss-support/releases/tag/3.0.2)

**Comment by MRchenkuan** [comment]
刚简单测试了下，主要问题修复了，大赞！感谢作者！

但是某些图片仍然存在这个问题，附件中我已经带上了出问题的图片（0733.JPG），直接上传仍然会报错，报错信息和上面一样，奇怪的是，该图片旋转90°保存之后，再上传就正常了。

而另一张的图片（0737.JPG）则表现正常，不知是否能抽时间看看（0733.JPG）这张图片的出错原因

不知是否是由于手机照片无法正确判断图片方向导致的？望您排查。

[归档.zip](https://github.com/IvanChou/aliyun-oss-support/files/523479/default.zip)



PS 报错信息：
Warning: filesize(): stat failed for /data/home/bxu2359040325/htdocs/wp-content/uploads/2016/10/IMG_0733-2-768x1024.jpg in phar:///data/home/bxu2359040325/htdocs/wp-content/plugins/aliyun-oss-1/aliyun-oss-php-sdk-2.0.7.phar/src/OSS/OssClient.php on line 1310

Fatal error: Uncaught exception 'OSS\Core\OssException' with message 'The size of `fileUpload` cannot be determined in multiuploadFile().' in phar:///data/home/bxu2359040325/htdocs/wp-content/plugins/aliyun-oss-1/aliyun-oss-php-sdk-2.0.7.phar/src/OSS/OssClient.php:1317 Stack trace: 
#0 phar:///data/home/bxu2359040325/htdocs/wp-content/plugins/aliyun-oss-1/aliyun-oss-wp.phar/src/Upload.php(59): OSS\OssClient->multiuploadFile('bucket-3', 'wp-content/uplo...', '/data/home/bxu2...', Array) #1 [internal function]: OSS\WP\Upload->uploadThumbToOss(Array) 
#2 /data/home/bxu2359040325/htdocs/wp-includes/plugin.php(235): call_user_func_array(Array, Array) 
#3 /data/home/bxu2359040325/htdocs/wp-includes/post.php(4891): apply_filters('wp_update_attac...', Array, 201) 
#4 /data/home/bxu2359040325/htdocs/wp-admin/includes/media.php(375): wp_update_attachment_metadata(201, Array) 
#5 /data/home/bxu2359040325/htdocs/wp-admin/async-upload.php(93): media_handle_upload('async-upload', 0)
#6 {main} thrown in phar:///data/home/bxu2359040325/htdocs/wp-content/plugins/aliyun-oss-1/aliyun-oss-php-sdk-2.0.7.phar/src/OSS/OssClient.php on line 1317

**Comment by IvanChou** [comment]
已处理，请试用 [3.0.3](https://github.com/IvanChou/aliyun-oss-support/releases/tag/3.0.3) 版本
