### ISSUE TITLE
无法启动插件

### ISSUE THREAD

**Issue by dz20161011** [IvanChou/aliyun-oss-support#19]
Parse error: syntax error, unexpected '
文件末尾增加?>后提示
Parse error: syntax error, unexpected '[' 

实在不会搞了 特来求助

**Comment by IvanChou** [comment]
插件版本是多少
php 版本是多少

**Comment by dz20161011** [comment]
3.0.0.2
5.3.28

**Comment by IvanChou** [comment]
没能复现问题

**Comment by baiqingju** [comment]
无法启用插件，因为它引起了一个致命错误（fatal error）。
Fatal error: Cannot declare class Extract_Phar, because the name is already in use in /data/wwwroot/xiu/wp-content/plugins/aliyun-oss/aliyun-oss-php-sdk-2.0.7.phar on line 103
使用的php7
