### ISSUE TITLE
同名文件上传时，后上传的图片的原图页面，会展示成先上传的那张图，缩略图则不受影响

### ISSUE THREAD

**Issue by MRchenkuan** [IvanChou/aliyun-oss-support#20]
此问题在未勾选“不在本地保存原图”功能时出现

**操作步骤：**
将两张不同的jpg图片A,B，先后命名为同一个名字然后先后上传，然后点击后上传的图片
预期：
显示为图片A
实际：
显示为图片B

**继续操作：**
在出错的这张图B下点“编辑图片”
预期：
展示出错的原图B
实际：
展示正确的原图A

**继续操作：**
在这张正确的原图A上，截取全图保存
预期：
保存为正确的原图A
实际：
保存为正确的原图A,但文件名相同的文件B，被覆盖成了A，同时 ，删除A,B任意一张图，都会导致两张图都打不开

**推断：**
WordPress自带的上传，能自动判断文件是否重名，并重命名文件，但上传到oss后，文件名无法判断文件是否重名，所以出现了后图覆盖前图的情况，望作者能抽空看看

**Comment by IvanChou** [comment]
确实会有这个问题，WordPress 原本会对同名文件加上 `-1` 一类后缀
但是本地不保留文件的时候就会破坏掉这一规则，OSS 本身对同名文件的处理是直接覆盖
目前我对此并没有比较好的解决方案，如果每次都去 OSS 拉取已存在的文件可能会让上传变得更慢，这里还是需要权衡一下

**Comment by IvanChou** [comment]
已经修复了 可以试一下最新版本
