### ISSUE TITLE
上传图片显示HTTP错误，但是实际上已经上传成功，只有缩略图无法显示出来。

### ISSUE THREAD

**Issue by zzw130** [IvanChou/aliyun-oss-support#23]
上传图片显示HTTP错误，但是实际上已经上传成功，只有缩略图无法显示出来。
PHP版本：5.4
插件版本：3.0.2

**Comment by zzw130** [comment]
#18 应该是和这个问题一样

**Comment by IvanChou** [comment]
已处理，请试用 [3.0.3](https://github.com/IvanChou/aliyun-oss-support/releases/tag/3.0.3) 版本
