### ISSUE TITLE
无法启用插件，因为它引起了一个致命错误（fatal error）。

### ISSUE THREAD

**Issue by baiqingju** [IvanChou/aliyun-oss-support#24]
无法启用插件，因为它引起了一个致命错误（fatal error）。
Fatal error: Cannot declare class Extract_Phar, because the name is already in use in /data/wwwroot/xiu/wp-content/plugins/aliyun-oss/aliyun-oss-php-sdk-2.0.7.phar on line 103
使用的php7

**Comment by IvanChou** [comment]
你是否还安装了一个其他跟 aliyun OSS 相关的插件？
可能是因为我们都使用了 aliyun-oss-php-sdk 导致 SDK 被引用了两次，触发了冲突

**Comment by pavilion1019** [comment]
我是同一个vps主机上由两个wordpress，所以安装了两次，出现这个问题，请问如何解决？

**Comment by IvanChou** [comment]
一个 vps 上装两个 wordpress 应该不会出现这个问题啊
难道你两个 blog 是使用同一套代码的两个不同的账户么？

**Comment by IvanChou** [comment]
重新看了下这个问题， 并不是重复引用 SDK 导致的这个问题
`Extract_Phar` class 也并不是 aliyun-oss-php-sdk 的一部分

@pavilion1019 能详细描述一下你是怎么触发这个 bug 的么，我需要复现一下

**Comment by IvanChou** [comment]
从 3.1.1 起不再使用 phar 包了，这个类似的问题应该不会再出现了
 
[3.1.1](https://github.com/IvanChou/aliyun-oss-support/releases/latest)
