### ISSUE TITLE
使用插件之后 网站无限加载

### ISSUE THREAD

**Issue by KanVivii** [IvanChou/aliyun-oss-support#25]
今天发现了插件！
点赞诶！

但是遇到点问题就是开启插件之后 设置应该没错误

然后网站就一直loading

一直loading

换过不同的bucket

关闭之后 立马打开网站

不知道为什么

还希望大大能建个群 大家一起交流呀

**Comment by IvanChou** [comment]
打开浏览器控制台看一下，看看是什么东西卡住了

群没要吧，最后总会变成瞎扯淡的地方，交流的话 issue 就够了，也可以给我发邮件啊 yiichou#gmail.com
