### ISSUE TITLE
支持 WooCommerce 吗？

### ISSUE THREAD

**Issue by iouio7453** [IvanChou/aliyun-oss-support#26]
您好，插件无问题，可用，赞！

插件的图片服务只支持 6 种样式，能够支持WooCommerce的图片服务吗？(shop_thumbnail、shop_catalog、shop_single)

**Comment by IvanChou** [comment]
如果 WooCommerce 的缩略图嵌入机制没有用什么黑科技
直接在 OSS 的图片服务中 增加 shop_thumbnail、shop_catalog、shop_single 三种样式应该就可以用了

如果不行的话，那么可能是它钩子嵌入的位置比较靠后，那就再给我反馈吧

**Comment by iouio7453** [comment]
您好，感谢您，成功了，谢谢！
