### ISSUE TITLE
OSS插件无法应用到Download Monitor插件

### ISSUE THREAD

**Issue by ly123567** [IvanChou/aliyun-oss-support#28]
正常媒体库上传可以及时更改链接，但使用Download Monitor快速上传的时候只会给出本应该上传到的链接，即upload/dlm_upload/xxxxx，而非直接给出OSS的链接。。。
希望能给这个比较多人用的插件做下优化QAQ

**Comment by IvanChou** [comment]
我去看一下 处理起来方便可以试着加一下，确实有冲突的话需要大改的话就没弃疗了哈~~~
欢迎 PR

**Comment by ly123567** [comment]
嗯，大概就是写文章那有个"插入下载"-"快速添加文件"，从那上传的文件不会自动改链接QAQ

**Comment by IvanChou** [comment]
呃呃呃 Download Monitor 这个插件是不可能被支持的，因为它工作的基础就是文件存放在本地

它的工作逻辑是：生成一个专用的下载链接，这个链接指向一个 php 工作的路由，然后由 php 从本地读取文件并返回。当文件不在本地的时候（比如 OSS 上），它是读取不到文件的，除非把文件又从 OSS 上下载到你的 WordPress 服务器上来。。。。

**Comment by ly123567** [comment]
哦哦这样啊，那我手动改链接吧，还是谢谢大大了QAQ

**Comment by IvanChou** [comment]
手动改链接么？你是指 快速添加文件 -> 手工输入 url 么？

**Comment by ly123567** [comment]
呃。。。我是指快速添加文件以后把它弹出来的那个链接里的"网站地址/wp-content/upload/"这一段修改成"OSS地址/目录"以后再保存，然后再去下载设置那里把这个链接"重定向到文件"

**Comment by IvanChou** [comment]
居然还有 重定向到文件 这样的选项 😂
其实可以不用辣么麻烦，它默认会把文件传到 dlm_uploads 是出于安全考虑，不希望这些文件被直接访问到。当你启用 "重定向到文件" 时，就已经和普通的附件上传没差别了，因此你并没有必要再使用它的上传工具了（它的「快递添加下载」）
所以我建议：从 「下载」->「新添加」这个页面来添加新下载，这个页面里面的 「上传文件」调用的是原生上传组件，完全支持 OSS 插件的效果，可以免去你手工修改 url 的麻烦

另外，在不启用「重定向到文件」这个选项的时候，OSS 那边如果开启了 「不在本地服务器上保留文件」，我相信结果是会让你崩溃的，哈哈哈~~

**Comment by ly123567** [comment]
呃，是这样的，非管理员权限只能用快速上传来添加东西QAQ
没有重定向的时候确实会出现INVALID_CONNECTION，奈何服务器那点空间根本不够装的(而且访问龟速)TAT只能出此下策了

**Comment by IvanChou** [comment]
这样啊。。。它里面的那个快速上传是它自己修改过的，取图片地址的钩子插入得很早，我对 url 的加工应该在它之后，所以它取到的是未处理的地址，改起来有点棘手
如果你可以自己改一改 Download Monitor 这插件的话，倒是很容易就可以实现你的需求，顺便还可以让它默认开启「重定向到文件」，用起来就很简单了

**Comment by ly123567** [comment]
嗯，但是比较麻烦的一点就是快速上传的"重定向"属性不好改，而且PHP小白不是很熟这些方面QAQ

**Comment by ly123567** [comment]
dalao.....上次提到的那个问题我用百度云Nginx的Rewrite重定向到OSS上了，但是又出现了新的问题。。。
就是提到的那个"快速上传"在传比较大的文件(测试的时候是6M)的时候会出现504，但文件出现在OSS上了，如果不勾选"不在服务器上保留文件"也会出现在服务器/wp-content/uploads/dlm_uploads/上不过不能在正常查看和访问(连百度云的在线删除都删不掉，只能用一些在线FTP比如景安的FTP工具强制删除)。
<img src="http://dl.dreamimd.com/2017/01/20170130161329.png">
但关掉OSS插件后上传同个文件正常，从管理员-下载界面添加也正常，请问一下这个是插件不兼容导致的吗？QAQ

**Comment by ly123567** [comment]
还有这种情况下应该怎么处理QAQ
