### ISSUE TITLE
增加对vpc环境的支持

### ISSUE THREAD

**Issue by Isongw** [IvanChou/aliyun-oss-support#29]
https://help.aliyun.com/document_detail/31837.html

ecs处于vpc环境时，访问oss稍微有一点小区别，能增加下对vpc环境的支持么

**Comment by IvanChou** [comment]
好滴 有空的时候我会加上

也欢迎 PR

**Comment by IvanChou** [comment]
sorry, 现在才提交这个更新，升级到最新版就可以用了

提交的内容： 51fd880

**Comment by Isongw** [comment]
感谢🙏，大神真是好人
