### ISSUE TITLE
文章插入图片的完整尺寸缺少origin标

### ISSUE THREAD

**Issue by xufan6** [IvanChou/aliyun-oss-support#30]
文章插入图片，尺寸选在“完整尺寸”，文章在预览时图片的srcset里没有用@!origin标

`<a href="https://osspath/images/2017/01/network-interfaces.png@!origin" target="_blank"><img class="aligncenter wp-image-295 size-full" src="https://osspath/images/2017/01/network-interfaces.png@!origin" alt="OpenWrt-Network-Interface-Overview" width="971" height="861" srcset="https://osspath/images/2017/01/network-interfaces.png 971w, https://osspath/images/2017/01/network-interfaces.png?x-oss-process=style/medium 300w, https://osspath/images/2017/01/network-interfaces.png?x-oss-process=style/medium_large 768w" sizes="(max-width: 971px) 100vw, 971px"></a>`

**Comment by IvanChou** [comment]
昂，其实这是我最近去掉的
当时加这个 origin 标识其实是为了一些网友有加水印和开启原图保护的需求特意添加的
这次 Aliyun 更新，有意把 图片处理 整合到 OSS 管理里面去（以前应该是分开的两套服务，要使用两个不同的域名，现在使用一个就够了，喜大普奔~）。
但是在这次升级中有很多遗留问题，原图保护 是老图片服务的一项功能，新的图片服务目前没有兹磁这个功能，就算用 origin 标签给图片加上了水印，某些人还是可以通过删掉尾巴就取到原图，于是这个 origin 就变成一个掩耳盗铃的手段了，嘎嘎~

**如果你确实有强烈的原图保护需求，建议暂时使用 3.0.x 的版本，等 Aliyun 解决这个问题**

如果你想使用新版，同时只需要图片有水印或者其他什么的预设需求并不需要保护原图，我想我可以把 origin 重新加上

**Comment by xufan6** [comment]
有几个地方没太理解：

> 原图保护 是老图片服务的一项功能，新的图片服务目前没有兹磁这个功能

现在在oss.console的图片处理 服务管理下就有原图保护的选项，是指这个还是老的图片服务嘛？

> 就算用 origin 标签给图片加上了水印，某些人还是可以通过删掉尾巴就取到原图

我现在用的时候删掉取不到原图啊，可以测试这个 http://ssssp.oss-cn-shanghai.aliyuncs.com/images/2017/01/6706033013_5972c121df_b.jpg@!medium

**Comment by baiqingju** [comment]
文章插入图片，尺寸选在“完整尺寸”，文章在预览时图片的srcset里用@!origin标后，一些幻灯插件不起作用，我想把@!origin标改成@!origin.jpg标,应该修改哪里？我想对原图做些样式修改，不想直接用原图。请高手指点一下，谢谢！

**Comment by IvanChou** [comment]
@xufan6 使我没有仔细读说明，原来要开启 老版配置同步才行，灰常感谢

我已经在新版本中修复这个问题了，请帮忙测试一下，顺便把 `origin` 换成了 `full`，因为 WordPress 自己使用的是 `full`
[3.1.2](https://github.com/IvanChou/aliyun-oss-support/releases/tag/3.1.2)

**Comment by IvanChou** [comment]
@baiqingju 升级到 3.1.2 就可以了

**Comment by baiqingju** [comment]
我想问一下，在后台编辑图像后，没有删除原图，在多媒体里边也不再显示原图，OSS里边原图还存在，如何让她编辑图像保存后删除原图

**Comment by IvanChou** [comment]
@baiqingju 确实不会触发删除原图，这是 WordPress 本身的逻辑，我只是监听相关动作，若它自己没有删除我也不会去删
你可以自己修改一下 顺便提个 PR
