### ISSUE TITLE
和EvernoteSync 插件似乎有点不协调

### ISSUE THREAD

**Issue by eexzy** [IvanChou/aliyun-oss-support#32]
在使用EvernoteSync插件，把图文同步到OSS后，在wp下，图片都无法显示。

原因是，如果图片是a.jpg, 在同步后，oss上的名字是a-100x43.jpg, a-150x150.jpg, a-300x300.jpg，唯独没有a.jpg。
如果不使用OSS插件，同步后，图片可以正常显示，且在code和wp媒体的图片名是a.jpg

奇怪的是，如果使用OSS，新建文章插入图片，图片都是没有问题的，而且在OSS的名字是a.jpg。

不知道为什么使用EvernoteSync后，图片上传到OSS就被自动标记了分辨率，在阿里OSS各种设置，也没有效果。

求帮助

**Comment by IvanChou** [comment]
图片是带上 a-100x43.jpg, a-150x150.jpg, a-300x300.jpg 之类是因为 WordPress 自身的图片处理功能，会将图片预裁剪成几种你可能会用到的尺寸

你遇到的问题可能是因为两个插件对同一处内容进行了操作，引起了某种冲突。

我自己会习惯性把自己写的钩子优先级设置得很低，所以我猜测是 EvernoteSync 嵌入的钩子先于我对内容进行了修改，进而导致我处理失败，于是你的 a.jpg 没有被传上去

**Comment by IvanChou** [comment]
@zhenxinfrozen 
Evernote 已经彻底关闭了 user token 获取了， EvernoteSync 我没发调试了
话说 Evernote 还能愉快的用下去么？

**Comment by zhenxinfrozen** [comment]
@IvanChou 恩，7，8年离不开的铁粉用户。
实现不了也无所谓了，我个人网站为了兼容evernote syn还是放弃了oss（反正也没人访问，用不用没区别）。
evernote现在的确挺没落的，算冷门了。没必要费心兼容它了，哈哈。（真爱粉很伤心）
另外一个 【分镜世界】网站。还是在用这个oss插件的。还是要感谢。
