### ISSUE TITLE
上传尺寸与预设的一致的图片是，无法显示缩略图

### ISSUE THREAD

**Issue by liyangio** [IvanChou/aliyun-oss-support#33]
上传图片后多媒体里面的缩略图不显示OSS上也没有该图片
PHP版本：7.0
插件版本：3.1.4

看了下历史issues，似乎与 #23 bug有些相似

**Comment by IvanChou** [comment]
吼 我去复现一下

**Comment by liyangio** [comment]
再补充下，我在wordpress设置的裁剪是`220*150`，上传这个大小的图片时就不显示缩略图，是一个灰块，接着我在oss中我刷新了一下也没看到刚上传的图片。

**Comment by IvanChou** [comment]
我尝试了一些情况，但是都没有能复现出你的问题

可以帮我确定几个条件么：

1. 你说的`缩略图`是不是指的 WordPress 的 `Thumbnail`（设置->多媒体 里的第一项）

2. 后台显示为灰块，插入文章中时图片能否正常显示出来（能选择的各种尺寸）

3. 你是否在插件的设置里面开启了图片服务？

4. oss中刷新没有看到上传的图片，是连原图都没有上传么？

**Comment by liyangio** [comment]
最近换账号了，忘记登录这个了。
针对你的4个条件：
1.我所说的缩略图就是Thumbnail
2.第二种情况没试过，但是我发现我在文章中插入图片后，大中小的尺寸都是220*133，并且完整尺寸不现实图片，点击自定义大小以后，编辑文章的模式可以看到图片，但是文章也却看不到图片。
参考链接：https://tvzr.com/how-to-replace-m-characters.html
后台图片：https://dn-liyang.qbox.me/image/github/img2.png
https://dn-liyang.qbox.me/image/github/img1.png
3.在插件的设置中开启了图片服务
4.oss中刷新后发现有原图，但是在资源库中的缩略图看不到
https://dn-liyang.qbox.me/image/github/img3.png
https://dn-liyang.qbox.me/image/github/img4.png
https://dn-liyang.qbox.me/image/github/img5.png
嗯，差不多都截图了，辛苦大神帮忙看下咯

**Comment by IvanChou** [comment]
sorry 最近比较忙，😅😅😅
我先 mark 一下，抽时间处理了再回复你

**Comment by IvanChou** [comment]
亲 抱歉现在才回复，最近都快忘了这个项目了
你这个是 https 配置的问题
你试着访问一下 https://oss.tvzr.com/img/2017/06/%5Em-e1499314512895.png?x-oss-process=style%2Flarge 这是你的 图片地址，会提示「您的连接不是私密连接」
应该是 oss.tvzr.com 这个域名没有配置 https 的证书
