### ISSUE TITLE
post-thumbnail的图片链接不是阿里原图图片样式，而是加了“-sizexsize”.jpg的形式，但不支持取到这个链接的图片

### ISSUE THREAD

**Issue by dameinliu** [IvanChou/aliyun-oss-support#34]
wordpress编辑器上传的文章正文图片可正确按图片样式方式在前端调用，但是特色图像(post-thumbnail)的调用是这种形式的img-530x640.jpg

**Comment by IvanChou** [comment]
讲道理不应该会出现这样的情况
从你的描述来看的话，有点像主题的作者偷懒（或者其他的原因），没有使用系统的方法获取 特色图像(post-thumbnail) 的路径，而是选择了自己拼链接

可以的话，请提供主题的文件给我确认一下 yiichou#gmail

**Comment by IvanChou** [comment]
主题是 authentic.zip 么？ 应该不是主题的问题
