### ISSUE TITLE
上传100M左右的视频，最后会出现http错误

### ISSUE THREAD

**Issue by cypcpycy** [IvanChou/aliyun-oss-support#35]
上传100M左右的Mp4视频格式的文件上传到100%以后会出现http错误

**Comment by IvanChou** [comment]
大文件我还没试过，不过确实出错的概率会很大
毕竟要在一个请求里面先把文件传上服务器，再从服务器传到 OSS

😂

**Comment by cypcpycy** [comment]
async-upload.php 
Failed to load resource: the server responded with a status of 404 (Not Found)
会出现这个错误

**Comment by IvanChou** [comment]
回头我也去试一下 100M 的文件

**Comment by IvanChou** [comment]
相关的问题及官方回复： https://wordpress.org/support/topic/http-error-on-upload-file-not-uploaded/

现在的上传模式是：本地 -> WordPress 服务器 -> OSS，根据网速不同，耗费的时间会比较长，但默认的 php 配置里面有一项 `max_execution_time: 30`， 如果 30s 内没有处理完就会中止服务

报 404 应该是因为文件上传失败了，被 WordPress 标记为没有这个资源，当前端的轮询再次去检测上传状态时，因为资源不存在于是报了 404

这个问题可以自己调节 php.ini 中的各项参数来解决，但是不是经常上传这么大的文件的话，感觉没必要

建议还是使用专业的 OSS 客户端上传这类大文件，获取 url 贴到 WordPress 文章中（虽然有点麻烦，但是可靠~）

**Comment by IvanChou** [comment]
相关的问题及官方回复： https://wordpress.org/support/topic/http-error-on-upload-file-not-uploaded/

现在的上传模式是：本地 -> WordPress 服务器 -> OSS，根据网速不同，耗费的时间会比较长，但默认的 php 配置里面有一项 `max_execution_time: 30`， 如果 30s 内没有处理完就会中止服务

报 404 应该是因为文件上传失败了，被 WordPress 标记为没有这个资源，当前端的轮询再次去检测上传状态时，因为资源不存在于是报了 404

这个问题可以自己调节 php.ini 中的各项参数来解决，但是不是经常上传这么大的文件的话，感觉没必要

建议还是使用专业的 OSS 客户端上传这类大文件，获取 url 贴到 WordPress 文章中（虽然有点麻烦，但是可靠~）
