### ISSUE TITLE
你好，我用了插件后  以前上传到服务器的图片的链接也被换成了阿里云oss的

### ISSUE THREAD

**Issue by bigning-techman** [IvanChou/aliyun-oss-support#36]
如果这样的话我以前的图片该怎么办呢？
还有是不是用了插件后以后的图片都要传到阿里云oss呢

**Comment by IvanChou** [comment]
以前的图片从后台看到的是会切换到使用 OSS 的 url，已经插入到文章中的链接不受影响

可以手动把以前的图片传到 oss 上对应的位置就可以了

用了插件以后图片会自动传到 oss 上，启用了 图片服务 只会上传原图，不会上传缩略图（因为已经不需要了），没有启用的话，会全部上传
