### ISSUE TITLE
Wiki 中的图片服务配置缺少规则

### ISSUE THREAD

**Issue by 0xJacky** [IvanChou/aliyun-oss-support#39]
您好，文档中给出的配置文件缺少了规则：full
导致开启图片服务后无法显示图片
<img width="324" alt="2017-08-26 12 08 33" src="https://user-images.githubusercontent.com/13096985/29738542-504bce48-8a57-11e7-888e-6014f6fa12d8.png">

**Comment by IvanChou** [comment]
哟 WordPress 加入 `full` 关键字了么
你的 WordPress 是什么版本，我去复现一下

**Comment by 0xJacky** [comment]
4.8.1
我自己添加了 full

**Comment by 0xJacky** [comment]
建议对 gif 取消使用图片处理，阿里云会把 gif 处理成 jpeg

发自我的 iPhone

**Comment by IvanChou** [comment]
阿里云这改版改得不行啊，以前预设样式是可以指定图片格式的
现在用参数的方式去处理，gif 没问题，但预设样式居然不行了

你不提我都没注意到这个坑

**Comment by IvanChou** [comment]
按你说的，修复了 gif 的问题
https://github.com/IvanChou/aliyun-oss-support/releases/tag/3.1.5
