### ISSUE TITLE
无法配合阿里云CDN使用

### ISSUE THREAD

**Issue by Zhehua-Hu** [IvanChou/aliyun-oss-support#40]
域名：example.com
网站：www.example.com
OSS外网地址：somebucket.blabla.example.com
OSS绑定域名：oss.example.com
CDN加速域名：cdn.example.com -> somebucket.blabla.example.com
CNAME解析：oss.example.com -> cdn.example.com
此时本插件的的bucket域名不能改为CDN地址，否则无法访问，不修改的话，保存的图片不会被CDN加速

**Comment by IvanChou** [comment]
可以设置为 CDN 地址啊，我现在就是这么用的
你的 CDN 配置是否正确

**Comment by IvanChou** [comment]
你先试一下通过 CDN加速域名 能否访问到你的资源
