### ISSUE TITLE
开启插件后网站没有任何变化

### ISSUE THREAD

**Issue by joegyx** [IvanChou/aliyun-oss-support#41]
上传图片没传到OSS，以前的图片链接也没变化

**Comment by IvanChou** [comment]
哈？ 你后台看下多媒体栏目下，图片的缩略图还都能显示出来么？不能的话，应该就是起作用了

WordPress 文章里面插入的图片地址是写死在数据库中的，所以这个插件对老文章来说没有多大帮助，除非你自己到数据库中替换掉老文章中的图片地址。后台「多媒体」栏目下的图片地址是动态的，所以启用后老图片应该就显示不出来了，可以选择把老的图片手动上传到 OSS 中来解决这个问题

这个插件会帮你把新上传的图片托管到 OSS，如果需要在老图片上生效，需要一些额外的操作（略带危险性那种，哈哈哈~~）

**Comment by vmvz** [comment]
@IvanChou 如果需要在老图片上生效，需要一些额外的操作

我想要 需要在老图片上生效， 有什么方案吗？

谢谢

**Comment by IvanChou** [comment]
https://github.com/IvanChou/aliyun-oss-support/wiki/How-to-handle-old-images
