### ISSUE TITLE
ultimate member插件的上传头像和背景无法上传成功，其他正常

### ISSUE THREAD

**Issue by jiqiukun** [IvanChou/aliyun-oss-support#42]
使用ultimate member插件时，上传头像等操作都是失败的，大致调试了一下，发现是选择图片时，生成临时文件的URL还是wp-content/uploads ，上传时却又变成OSS的URL，导致上传图片失败，请问一下这个冲突怎么解决？

**Comment by IvanChou** [comment]
我试着复现下，看看能不能处理

**Comment by IvanChou** [comment]
ultimate member 使用了自己写的上传工具，而非调用 WordPress 原生的上传工具，这导致我没法监听它的上传请求并把文件上传到 OSS

获取图片地址的时候，又略微简单粗暴，配置了 url 规则的都替换了，导致图片取不到了

这个有点尴尬了，我是应该支持 ultimate member + OSS 呢？ 还是排除掉 ultimate member 的图片呢？

**Comment by IvanChou** [comment]
https://github.com/IvanChou/aliyun-oss-support/blob/master/CHANGELOG.md#%E7%89%88%E6%9C%AC%E5%8F%B7-323

高级选项中 exclude 填入 `/ultimatemember/` 即可
