### ISSUE TITLE
插件不支持buddypress。

### ISSUE THREAD

**Issue by mr-ant** [IvanChou/aliyun-oss-support#44]
如题，启用BuddyPress之后，不能修改头像以及背景图。可以的话，下个版本发布时可以修复一下吗？

**Comment by IvanChou** [comment]
#42 
应该和这个的问题差不多

**Comment by jiangnanfei** [comment]
刚测试了一下，BuddyPress上传图片之后会自动裁切成多个文件并且重命名文件，-bpfull和-bpthumb两个文件，头像是裁切之后的-bpthumb文件。现在插件是只上传源文件到服务器，我建议直接屏蔽插件对
BuddyPress的作用，直接将生成的文件传到阿里云就好了。 在BuddyPress下我还用了buddydrive这个插件，同样启用阿里云oss之后无法生成缩略图了。应该是BuddyPress是一样的问题。不知道我说的可行不？谢谢。

**Comment by IvanChou** [comment]
https://github.com/IvanChou/aliyun-oss-support/releases/tag/3.2.0

现在支持了
