### ISSUE TITLE
能否支持 css、js等缓存文件上传呢？

### ISSUE THREAD

**Issue by llity** [IvanChou/aliyun-oss-support#45]
目前发现只能上传图片哦。谢谢

**Comment by llity** [comment]
因为合并了css和js等文件在uploads文件夹，但是到oss上看，没有自动上传这个文件，所以想实现uploads整个文件夹的上传。谢谢

**Comment by IvanChou** [comment]
你的 css, js 是怎么上传的呢？是通过 WordPress 后台的上传工具么？

**Comment by llity** [comment]
@IvanChou 有的js css 压缩minify插件自动生成的哦，然后保存到了wp upload目录。能否让你的插件能上次这个upload目录那就真的完美了。

**Comment by llity** [comment]
@IvanChou 一些插件会储存一些图片、js、css等到 wp-content 目录，能否给oss添加一个手动上传 wp-content 目录的内容到oss中去呢？谢谢

**Comment by IvanChou** [comment]
嗯 这个问题目前可以通过现有方案完美解决的：

第一种方案：
升级到最新版，使用高级选项里面的 exclude 选项过滤掉这些特定的目录，不使用 OSS 来托管

第二种方案：
https://github.com/IvanChou/aliyun-oss-support/wiki/How-to-handle-old-images
按这篇文档设置 OSS 回源，来避免这一系列的 OSS 文件找不到的问题

第三种方案：
使用插件里面提供的 hook`action: oss_upload_file`, 去修改不兼容的插件，帮它们完成文件上传 OSS 的步骤
