### ISSUE TITLE
自己 add image size()  的名称无法被插件调用啊

### ISSUE THREAD

**Issue by zhenxinfrozen** [IvanChou/aliyun-oss-support#46]
自己命名的缩略图名称，插件无法传递给oss。
看了一下代码 UrlHelper.php 

> foreach(array('thumbnail', 'post-thumbnail', 'medium', 'medium_large', 'large', 'full') as $style ) {

这里只有WP默认的缩略图名称，
我自己在后面添加了主题注册和自己注册的名称后，才能正常使用。

请问这的确需要这么改动才能起作用吗？
还是我的设置问题吗？

**Comment by IvanChou** [comment]
是的 的确需要这么改动才行
之前有想过怎么解决这个问题，在主题里面自定义图片样式还是挺常见的
后来发现没人提这个问题，大概是大家都没遇到，于是就没弄了
哈哈哈~~ 欢迎提交 PR

**Comment by zhenxinfrozen** [comment]
我不会改后台自定义，哈哈（本人只是个美术，代码只会摸索的折腾折腾）
只能很笨的在相应的代码上添加了自己的样式了。
感觉觉得这个功能还是很有必要的吧。
怎么说，大部分主题都会有些自定义的 缩略图样式吧。

我觉得你这个OSS插件。最吊炸天的点就是这个利用oss图片样式处理功能。
如果一般人没有注意到这个自定义样式的问题。
无法使用真是太遗憾了。

不过可能有些人，连自己的缩略图名称也不知道在哪里找吧。
估计更完善的做法可能需要插件自己去function里搜索所有的缩略图样式名称，然后添加。这样最完美。

**Comment by IvanChou** [comment]
https://github.com/IvanChou/aliyun-oss-support/commit/be288a88b977ac36be1a15ed005f2dd123ee831e
