### ISSUE TITLE
无法上传

### ISSUE THREAD

**Issue by xiqingongzi** [IvanChou/aliyun-oss-support#5]
AK.SK都设置好了，但是无法上传任何文件。不止图片、上传，，没有提示。
![qq 20150429223528](https://cloud.githubusercontent.com/assets/6560019/7393397/11e01856-eec0-11e4-99aa-f256726a89d5.jpg)
![qq 20150429223559](https://cloud.githubusercontent.com/assets/6560019/7393410/20310258-eec0-11e4-8126-920b74ba8ff2.jpg)

**Comment by IvanChou** [comment]
su mi ma sen ~  
最近一直没有跟进这个插件的反馈 包括之前的几个 BUG
下周二之前我会抽时间处理
