### ISSUE TITLE
这个能否做到双向同步？

### ISSUE THREAD

**Issue by zhujitop** [IvanChou/aliyun-oss-support#54]
现在是在wordpress上传的图片会同步到阿里云oss里面去，
如果我单独上传图片到阿里云oss里面，
在wordpress网站这边显示出单独在阿里云oss上传的图片。
这样对多个网站用同个附件挺有帮助的。

不知道阿里云oss是否支持这样做？

**Comment by IvanChou** [comment]
那就是把 OSS 当共享网盘用嘛，网上已经有这样的轮子了
Wordpress 这边需要做的就只是替换一下图片的链接，把插件里面上传部分的代码注释掉就可以了

**Comment by IvanChou** [comment]
https://github.com/search?utf8=✓&q=oss+sync&type=
