### ISSUE TITLE
与the7不兼容

### ISSUE THREAD

**Issue by yxy1992** [IvanChou/aliyun-oss-support#56]
与the7不兼容 开启插件  界面就变了   jhdcl.com

**Comment by yxy1992** [comment]
![_2018-03-14t07-26-22 926z](https://user-images.githubusercontent.com/20100632/37388933-5335bad6-279d-11e8-940e-ba086fc9bf86.png)

**Comment by yxy1992** [comment]
![_2018-03-14t07-36-14 978z](https://user-images.githubusercontent.com/20100632/37388966-7272efd6-279d-11e8-986c-9d56e924700c.png)
原先这样

**Comment by IvanChou** [comment]
https://github.com/IvanChou/aliyun-oss-support/releases/tag/3.2.3

3.2.3 应该已经可以解决这个问题了
