### ISSUE TITLE
不兼容wp-less

### ISSUE THREAD

**Issue by malagebidi** [IvanChou/aliyun-oss-support#58]
你好，

我的主题自带了wp-less功能，他会把所有的less css文件合并后在cache文件夹生成一个总的css文件供主题使用。不过在启用了aliyun-oss-support这个插件后，less的功能失效了，而且其中一个css还被替换城了阿里云oss的地址，麻烦请查看一下。

![less](https://user-images.githubusercontent.com/726456/38425623-f8f0e8fa-39e6-11e8-8031-a7bdcb65f0fe.JPG)

**Comment by IvanChou** [comment]
不兼容插件列表有新增了一员🤣

**Comment by IvanChou** [comment]
https://github.com/IvanChou/aliyun-oss-support/releases/tag/3.2.3

3.2.3 可以解决这个问题了
