### ISSUE TITLE
可以排除uploads下的某个目录吗

### ISSUE THREAD

**Issue by ebsinori** [IvanChou/aliyun-oss-support#61]
我的主题会自动在uploads目录下生成css文件，上传不到oss上，但诡异的是读取的时候却读了oss拼接后的路径，导致加载不到css。
所以想问下有没有办法让插件排除某个目录，该目录下的都不上传到oss，读取的时候也不在oss上读。
或者能告诉我在什么地方可以设置吗？我自己弄也行。

**Comment by IvanChou** [comment]
现在可以了 
https://github.com/IvanChou/aliyun-oss-support/releases/tag/3.2.3
