### ISSUE TITLE
用了这个插件，本地就不能存储了？

### ISSUE THREAD

**Issue by zhujitop** [IvanChou/aliyun-oss-support#62]
开启了这个插件,上传的图片就直接到阿里云oss了。
本来服务器没有存储图片。
一旦把插件关闭了，图片就不显示了。

不知道是我设置不对，还是插件就是这样的？

如果就是这样的，希望修改一下啊，图片存储在本地服务器，也同时上传到阿里云oss了。

**Comment by IvanChou** [comment]
配置里面有一项 『不在本地服务器上保留文件』不要勾选就好了

当然，之前勾选时已经删掉的图片是回来了，你需要手动处理一下
