### ISSUE TITLE
关于图片编辑

### ISSUE THREAD

**Issue by shimakazeDivine** [IvanChou/aliyun-oss-support#63]
媒体库以及各处的图片编辑失效了，是不是因为4.9.6wp版本的原因呢

**Comment by IvanChou** [comment]
我无法复现这个问题呢

**Comment by shimakazeDivine** [comment]
感谢回复，目前使用了3.2.1版本，发现几个问题
我的设置是这样的 香港数据中心 内网 不在本地服务器保留文件 启用图片服务

1. 图片依旧无法编辑 从媒体库进入图片编辑 会加载不出图片 或者 外观-自定义-站点身份 修改站点图像时裁剪 会报错（在裁剪您的图像时发生了错误。）
2.无法删除oss内文件 从媒体库删除某个文件后 oss内的文件依旧存在 我使用的是同一个AccessKey，应该不会是权限问题
3.感谢维护

**Comment by shimakazeDivine** [comment]
问题1已解决 不使用我自己的域名便可以编辑，问题2依旧存在 新问题，图片服务失效，开启图片服务oss内依旧会有多个图片文件

**Comment by shimakazeDivine** [comment]
问题2 在媒体库中删除图片，不会删除oss内的文件是不正确的 实测会删除，但是只会删除额外生成的小图片，原图不会删除

**Comment by shimakazeDivine** [comment]
问题2 如果我关闭不在本地服务器保留文件选项，文件便会正常删除 但是即使我开启这个选项，本地服务器依旧会保存文件 问题3 图片服务经过测试，无论是否开启都会生成额外小图

**Comment by IvanChou** [comment]
同 #72 

这是 3.2.1 版本的一个 bug，在 3.2.2 里修复了，『不在本地服务器保留文件』已经被移到隐藏配置里面去了，不太建议开启

话说，你测试得好仔细
