### ISSUE TITLE
可视化编辑器添加图片时设置具体的宽高，会加载不出来图片，请看看

### ISSUE THREAD

**Issue by badongdyc** [IvanChou/aliyun-oss-support#64]
![image](https://user-images.githubusercontent.com/17975624/41020319-03bdc568-6995-11e8-8c51-6ba66e28bb55.png)
![image](https://user-images.githubusercontent.com/17975624/41020339-181a1e80-6995-11e8-93e2-3f1db2c7fb0d.png)
输入“thumbnail”, “medium”, “large”, “full” 这几个就是正常的，麻烦看看 @IvanChou @mosuke5 @liliang13 @darklx @0xJacky

**Comment by IvanChou** [comment]
啊 现在还支持直接输入尺寸了，汪汪汪？ WordPress 这么人性化了都

**Comment by IvanChou** [comment]
虽然不清楚你这个『可视化编辑器』是你的主题提供的还是某个插件提供的，但是你可以先升级到 3.2.1 试一试，或许正好解决了这个问题
