### ISSUE TITLE
服务器本地不保留文件时，会导致 OSS 上对应的文件删不掉

### ISSUE THREAD

**Issue by IvanChou** [IvanChou/aliyun-oss-support#65]

**Comment by malagebidi** [comment]
确实是这样，不太友好。

**Comment by tyt2y3** [comment]
我想使用OSS的原因之一就是想節省硬盤空間啊
能論述一下導致問題的原因嗎?
能力範圍之內的話希望我能幫忙修復
因為以我理解, wordpress數據庫中是有儲存attachment的資料呀
如果再加一個post meta 在attachment之上, 顯示 OSS的源資料
是不是就成了?

**Comment by IvanChou** [comment]
@tyt2y3 

最主要还是 hook 选用的问题，目前删除使用的是 `wp_delete_file`  这个 filter，而当本地文件不存在的时候不会触发到这段逻辑，因此就导致了删除失败

所以，最优的解决方案应该是找一个合适的位置更靠前的 hook，但是 hook 的位置约靠前，需要考虑的情况就更多，可能工作量主要是在测试上。

**Comment by tyt2y3** [comment]
我選用了 delete_attachment 解決了這個問題
#88
