### ISSUE TITLE
更换站点图标时无法加载图标，提示NoSuchKey

### ISSUE THREAD

**Issue by AngusZhao2017** [IvanChou/aliyun-oss-support#67]
图标是已经成功上传的，阿里云OSS、WordPress后台媒体中也都可以正常显示，但更换站点图标时会无法加载，此时单独查看该图标时发现，**网址后部由原来的/2018/07/icon.png变为了/2018/07/cropped-icon.png**，可能是会自动裁剪图片吧，但裁剪过的图片在阿里云OSS中不存在，所以会提示报错NoSuchKey，但网站的其它图片（例如文章等）均正常（可能是不需要裁剪？？）。看了半天代码，也不知道哪里出了问题，麻烦查看下，谢谢~！插件已启用“图片服务”，未启用“图片预设样式”以及“原图保护”。详细见附图。

更新：查看服务器后台发现，上传的文件中既有由原图标生成的缩略图，也有裁剪后的图标生成的缩略图，但阿里云OSS里仅有原图标，所以调用cropped-icon.png时会报错……但我不明白为啥…有点懵…详见最后两张图片。

![4](https://user-images.githubusercontent.com/34939286/43380225-f0df3cea-9402-11e8-945a-8dc0ab435398.jpg)
![5](https://user-images.githubusercontent.com/34939286/43381544-935348d2-9407-11e8-9ad0-158b1d4146d2.jpg)
![6](https://user-images.githubusercontent.com/34939286/43380227-f1dbc73a-9402-11e8-8341-41187a71ba8d.jpg)
![7](https://user-images.githubusercontent.com/34939286/43380228-f259b546-9402-11e8-801b-a6506768e792.jpg)
![9](https://user-images.githubusercontent.com/34939286/43382065-3c512a8e-9409-11e8-9078-19f06bd68f65.jpg)
![10](https://user-images.githubusercontent.com/34939286/43382067-3e6f5d22-9409-11e8-88f0-f2675248edfb.jpg)

**Comment by IvanChou** [comment]
1. 「站点图标」这个功能是你的主题提供的，还是某个插件
2. 你应该使用的是 3.1.x 的版本吧，先升级到 3.2.x，3.2 改了 hook 机制，就是为了处理这类问题

**Comment by AngusZhao2017** [comment]
我升级到了3.2.1版本了……但是…图片不能正常上传了……
提示：

> HTTP错误

环境已经重建过了，没什么用……
也不明白是什么问题，麻烦再帮忙看下~

我的环境是：
phpmyadmin-4.4
php-7.0
pure-ftpd-1.0.47
mysql-5.5
apache-2.4
![1](https://user-images.githubusercontent.com/34939286/43562566-e4b53e0c-964f-11e8-811e-eb5f55ce6c9c.JPG)
