### ISSUE TITLE
请问去哪里下载图片样式配置文件？

### ISSUE THREAD

**Issue by AngusZhao2017** [IvanChou/aliyun-oss-support#68]
Wiki里提到

> 勾选『图片预设样式』后，会出现『点击下载图片样式配置文件』的链接，将配置文件下载下来导入到阿里云上即可

但是我在插件里勾选了『图片预设样式』后，并没有出现下载配置文件的链接
麻烦帮忙看下~
emmm
![8](https://user-images.githubusercontent.com/34939286/43380832-226022be-9405-11e8-9973-b3d13435225d.jpg)

**Comment by AngusZhao2017** [comment]
刚看了下…我的版本确实是3.1.6诶……

话说，
https://github.com/IvanChou/aliyun-oss-support里面的超链接

> 当前版本
Stable: 3.2.1

和

> 下载
latest release

都是默认跳转至3.1.6版本里了……所以我没有下载到最新版3.2.1……
我刚刚通过改网址的方法下载到啦，麻烦更新下超链接哈哈哈~

**Comment by IvanChou** [comment]
谢谢提醒 我的锅
