### ISSUE TITLE
配置错误时，应该给出异常提醒

### ISSUE THREAD

**Issue by ccgitgit** [IvanChou/aliyun-oss-support#69]
WordPress 4.9.7
Apache 2.0 
PHP 7.0
按照要求设置了OSS和wordpress插件，
为了方便测试OSS还开了读写，内外网地址都试过，不同浏览器也试过
插件保存配置时候没有报错，但是图片还是在本地，不到OSS

ECS是新开的 ECS上难道还需要开通某些权限吗？

**Comment by AngusZhao2017** [comment]
我的环境也是这样的，但是上传图片时候会提示HTTP错误……不知道为什么

**Comment by IvanChou** [comment]
不需要 ECS 开通什么权限
会不会是 AccessKeySecret 有问题，在报错这方面我没有下功夫，直接捕获了异常所以你没有看到报错

**Comment by kaho100** [comment]
直接勾选“不在本地服务器保留文件”，一了百了

**Comment by malagebidi** [comment]
刚刚从3.1.5升级到3.2.2，竟然报500了

**Comment by IvanChou** [comment]
@malagebidi 呃 讲道理应该不会呀 能提供报错信息么？

**Comment by malagebidi** [comment]
昨天研究了一会，在error log里面找到了一些信息：
`Uncaught ImagickException: unable to open image '/home/default/wp-content/uploads/2018/10/server-90389_1920-135x90.jpg': No such file or directory @ error/blob.c/OpenBlob/2712 in /home/default/wp-content/plugins/imagemagick-sharpen-resized-images/imagick-sharpen-resized-images.php:142`

就是我用ImageMagick Sharpen Resized Images来锐化缩放的图片，应该是锐化的时候图片已经传去OSS了。我把该插件add_filter部分改了一下：
`add_filter('image_make_intermediate_size','imagick_sharpen_resized_files',900);`
变成
`add_filter('image_make_intermediate_size','imagick_sharpen_resized_files',9);`

反正现在是可以运行了，不知道方法对不对。或者我想的是aliyun-oss-support能不能把上传的执行顺序靠后一些，这样就可以兼容shortpixel这类优化图片的插件了。

**Comment by IvanChou** [comment]
@malagebidi nice work！
之前没想到过这个问题，我的锅

**Comment by IvanChou** [comment]
#83 
#85

**Comment by IvanChou** [comment]
https://github.com/IvanChou/aliyun-oss-support/releases/tag/3.2.6
