### ISSUE TITLE
3.2.1版本上传文件时报错：“HTTP错误”

### ISSUE THREAD

**Issue by AngusZhao2017** [IvanChou/aliyun-oss-support#70]
与 #13 中的情况类似，如果储存路径留空或者为 / （保存到根目录）就会报错，但事实上文件是被正常上传至服务器和阿里云OSS中的，现在我暂时的方法是在阿里云OSS中新建一个文件夹来存放附件，希望抽空修复一下嘿嘿~谢谢！
![1](https://user-images.githubusercontent.com/34939286/43573496-6894aff4-9674-11e8-82bd-62b6032a79bb.JPG)

**Comment by IvanChou** [comment]
如果我说我忘了当时怎么修复的…… 会不会被打 🤣

**Comment by AngusZhao2017** [comment]
可以把安装说明改一下：不支持存放在Bucket的根目录，哈哈哈哈

**Comment by IvanChou** [comment]
已经修复了 我的锅
