### ISSUE TITLE
开启图片服务后还是会上传缩略图到 OSS

### ISSUE THREAD

**Issue by hiwyx** [IvanChou/aliyun-oss-support#72]
WordPress 4.9.8
aliyun-oss-support 3.2.1
配置如下图：

![屏幕快照 2018-08-09 下午2.15.41.png](https://i.loli.net/2018/08/09/5b6bdcae23685.png)
![屏幕快照 2018-08-09 下午2.15.59.png](https://i.loli.net/2018/08/09/5b6bdcc679bfd.png)

**Comment by junyuexin** [comment]
我升级到3.2.1之后也出现这个情况了。还有就是能不能下个版本增加一个插件自动更新功能。插件自动更新功能的地址https://github.com/YahnisElsts/plugin-update-checker，可以先测试一下。谢谢。可惜我不太会用git，不然我就做个分支推送给你。

**Comment by IvanChou** [comment]
好巧的 我也有这个问题 🙈🙈🙈

**Comment by IvanChou** [comment]
3.2.2 已修复

@junyuexin 3.2.2 已经用上了，感谢
