### ISSUE TITLE
希望优化与OSS之间的传输方式

### ISSUE THREAD

**Issue by AlbertETA** [IvanChou/aliyun-oss-support#73]
现在插件只能填一个OSS地址，期待**增加一个OSS地址**，以便：
当OSS和ECS处于同一地域同一区域时，希望在插件中多添加个能通过**ECS内网上传附件至OSS**的地址，内网带宽大，传输速度也快。这样合理使用了内网的带宽，同时减少了ECS对上行外网的珍贵带宽资源的占用。
然后在**外网访问ECS上的网站时使用OSS外网访问地址来加载OSS上的附件**，因为此时若使用OSS内网地址将导致外网用户无法加载附件。

**Comment by IvanChou** [comment]
有这个功能啊

![image](https://user-images.githubusercontent.com/2182089/44324558-9a895880-a488-11e8-95bb-4d8fe8ebafc0.png)

插件与 OSS 的通讯跟你填的 Bucket Host 是没有关系的，Bucket Host 只是用来填入你的自定义域名，就算留空也会 fallback 到一个默认的 url

如果 ECS 在内网，勾选启用 internal/内网 就好了
