### ISSUE TITLE
插件自动更新有问题

### ISSUE THREAD

**Issue by junyuexin** [IvanChou/aliyun-oss-support#74]
https://chou.oss-cn-hangzhou.aliyuncs.com/aliyun-oss-3.2.2.zip
这个文件无法下载，无法更新，你自己可以测试一下，或者改成这个地址也可以
https://github.com/IvanChou/aliyun-oss-support/releases/download/3.2.2/aliyun-oss-3.2.2.zip

**Comment by junyuexin** [comment]
这个地址其实也可以放置在github里边
https://chou.oss-cn-hangzhou.aliyuncs.com/aliyun-oss/plugin.json

**Comment by IvanChou** [comment]
sorry 地址写错了，应该是 https://chou.oss-cn-hangzhou.aliyuncs.com/aliyun-oss/aliyun-oss-3.2.2.zip

本来是直接用 github 的，还不用去同步，但是如果后台触发了更新检测，github 网络正好抽风一下，用户的后台可能卡白板。考虑到大部分用户都是国内的，还是放 aliyun oss 吧
