### ISSUE TITLE
OSS图片保护后无法显示

### ISSUE THREAD

**Issue by zxmlysxl** [IvanChou/aliyun-oss-support#75]
OSS中图片加了个水印，wordpress里用插件无法获取到加了水印的图片，只能获取原图；

**Comment by IvanChou** [comment]
https://github.com/IvanChou/aliyun-oss-support/wiki/How-to-use-Image-Service#%E5%8E%9F%E5%9B%BE%E4%BF%9D%E6%8A%A4

1. 插件后台启用 『预设图片样式』+ 『原图保护』
2. 在阿里云后台图像处理里面给需要加水印的样式加上水印
3. 为了避免原图被访问到，阿里云后台开启『原图保护』

设置好之后，在文章新插入的原图链接会带上 full 的样式后缀，获取的就是带水印的原图了。之前文章里面已经插入的原图因为 url 是硬编码保存的，所以会直接无法访问，解决方法有两个：

1. 设置重定向，把原图 url 重定向到 url?x-oss-process=style/full
2. 编辑文章，把失效的图片链接删掉，重新插入
