### ISSUE TITLE
不支持CDN，希望能增加一个修改源地址的功能

### ISSUE THREAD

**Issue by LiuChangFreeman** [IvanChou/aliyun-oss-support#76]
文章中的图片链接直接暴露了oss域名，例如：
http://liuchangfreeman-xyz.oss-cn-beijing.aliyuncs.com/2018/08/2018-08-28-1-1024x653.png
这样就无法开启CDN加速了，我已经配置成功的CDN链接为：
http://static.liuchangfreeman.xyz/2018/08/2018-08-28-1-1024x653.png
希望能够提供一个替换链接中host的方法

**Comment by IvanChou** [comment]
![image](https://user-images.githubusercontent.com/2182089/44970923-4b621e00-af86-11e8-85f1-ad9aee1c3298.png)

这个位置填 static.liuchangfreeman.xyz
