### ISSUE TITLE
缩略图生成的大小不一致

### ISSUE THREAD

**Issue by netwboy** [IvanChou/aliyun-oss-support#77]
生成的缩略图大小不一致，在wp的媒体设置中，已经设置了大小，并勾选了总是裁剪缩略图到这个尺寸，
阿里云oss那边的规则thumbnail样式设置的是image/resize,m_pad,w_480,h_300，但wordpress文章的缩略图大小还是不一致，请问是什么原因呢

**Comment by IvanChou** [comment]
插件启用 『图片预设样式』之后，可以下载当前 WordPress 中使用的样式的配置文件

https://github.com/IvanChou/aliyun-oss-support/wiki/How-to-use-Image-Service#%E5%90%AF%E7%94%A8%E9%A2%84%E8%AE%BE%E6%A0%B7%E5%BC%8F

你看看这里面的 thumbnail 样式是不是  image/resize,m_pad,w_480,h_300

插件不会干预图片尺寸样式，如果出现你的说问题可以确认是 OSS 里的样式设置与 WordPress 需要的样式不一致

**Comment by netwboy** [comment]
oss和wordpress媒体设置里的大小都是一致的呢。

**Comment by IvanChou** [comment]
https://help.aliyun.com/document_detail/44688.html?spm=a2c4g.11186623.6.1147.65a1b5d0CbyQee

m_pad 是固定宽高，缩略填充，是『填充』，你应该用 m_fill 才对吧

2 楼的文档里有提到的，你可以直接下载配置导入到 阿里云 OSS 里面，或者下载配置和你现在的配置比对一下，然后手动设置也行的
