### ISSUE TITLE
旧版本2.3.2 升级到新版3.2.2后主页无法打开

### ISSUE THREAD

**Issue by klu7** [IvanChou/aliyun-oss-support#78]
今天尝试从2.3.2升级到3.2.2时（删除后，按以前配置安装新版本），网站主页无法打开。 且3.2.2的版本找不到配置OSS独立域名的地方。
重新装回2.3.2后主页显示恢复正常

**Comment by IvanChou** [comment]
2.3.2? 15年的版本么？
你的php 版本是多少的呢？能否提供报错信息

**Comment by IvanChou** [comment]
关于自定义域名：
https://github.com/IvanChou/aliyun-oss-support/wiki/Quick-start#%E4%BD%BF%E7%94%A8%E8%87%AA%E5%AE%9A%E4%B9%89cdn-%E5%9F%9F%E5%90%8D

**Comment by klu7** [comment]
> 2.3.2? 15年的版本么？
> 你的php 版本是多少的呢？能否提供报错信息

恩 应该是15年的时候安装的插件，php5.5，主页一直处于加载状态，阿里云虚拟机，不知怎么查看报错信息。

**Comment by IvanChou** [comment]
`define( 'WP_DEBUG',  true ); ` 开启 debug，看看报啥错

**Comment by klu7** [comment]
> `define( 'WP_DEBUG', true ); ` 开启 debug，看看报啥错
安装3.2.3后 访问正常。
