### ISSUE TITLE
点击下载下载图片样式配置文件之后出现错误

### ISSUE THREAD

**Issue by mzxhtml** [IvanChou/aliyun-oss-support#79]
![image](https://user-images.githubusercontent.com/32251251/47892152-252b0280-de91-11e8-969c-7224cc7bdf63.png)

Warning: Cannot modify header information - headers already sent by (output started at /www/wwwroot/htmlzj_com/wp-admin/menu-header.php:159) in /www/wwwroot/htmlzj_com/wp-includes/pluggable.php on line 1219

**Comment by IvanChou** [comment]
WordPress 版本是多少呢

**Comment by IvanChou** [comment]
在 [3.2.3] 中已经修复
