### ISSUE TITLE
让插件更好的支持中文

### ISSUE THREAD

**Issue by hairui219** [IvanChou/aliyun-oss-support#8]
您好，

因为插件不支持中文图片，因此应用之后发现部分图片无法显示出来。
在应用插件之前，网站已经上传几百于张图片，多数图片为中文命名。按照迁移流程完成图片服务器的设置之后，有部分图片显示不出来。因此进行了几天的追踪，发现为oss-support.php文件中的205行

```php
    $filename = basename($data['file']);
```

php中的basename函数不支持中文所致。因此尝试进行了修复，替换为

```php
$filename = preg_replace('/^.+[\\\\\\/]/', '', $data['file']);
//网上搜寻的用于修复basename不支持中文的修复方案
```

目前工作基本正常。

**Comment by IvanChou** [comment]
感谢反馈 随后会更新
