### ISSUE TITLE
在停用插件的情况下发布文章，重新启用插件，里面的图片会不显示

### ISSUE THREAD

**Issue by hakw77** [IvanChou/aliyun-oss-support#81]
PHP7.2 + Nginx 1.15
试用过程中发现，在启用并配置好插件后，新发布文章中的图片都是OSS地址，这个没问题；
1、此时停用插件，发布一篇新文章，可以看到图片URL都是本地地址；
2、启用插件，此时发现刚才发布的文章地址变成了OSS地址，全部无法显示；因为我刚才发布的文章是在停用插件的情况下发布的，应该没有上传到OSS。
3、而且发现以前的图片URL地址也会变成OSS地址导致无法显示；

**Comment by IvanChou** [comment]
这是 WordPress 绕不开的一个问题，文章中插入的图片地址是绝对地址，而主题调用的图片地址是实时生成的。
目前来看，有两种解决方案
1. 手动去上传 OSS 上没有的图片，配置好了就少去动插件
2. Storage Path 设置成 /wp-content/uploads,  然后配置 OSS 回源

最近也在考虑抛弃 SDK 上传文件这种方式，改用 OSS 回源 或者 磁盘挂载，不过没有太多时间去折腾

**Comment by IvanChou** [comment]
https://github.com/IvanChou/aliyun-oss-support/wiki/How-to-handle-old-images
