### ISSUE TITLE
后台上传和现实图片正常，前台无法显示，srcset为什么没有替换？

### ISSUE THREAD

**Issue by dream80** [IvanChou/aliyun-oss-support#83]
看了一下源代码，图片的src正常替换成了oss地址，但是srcset里面还是本地的地址，所以当加载srcset里的地址时无法正常现实图片，为什么会这样呢？ 我看插件里面有替换srcset的代码，为什么显示文章的时候没有替换呢？

**Comment by 91xtw** [comment]
> 昂？ 3.2.4 么？ 不应该啊
> 能否提供下案发现场，我需要试着复现一下

我也一样的，他要主号key才可以的，子号rem是不行的。我换了主号就可以了。
