### ISSUE TITLE
媒体上传100%时需要等待较长一段时间

### ISSUE THREAD

**Issue by JFC1112** [IvanChou/aliyun-oss-support#84]
媒体上传进度条到100%时需要等较长一段时间（这个时间应该是网站在上传到OSS的过程），
若文件较大那就要等好久会给人造成假死的感觉，比如我上传个100M的视频，进度条100%后要卡住几分钟

如果上传进度条能做相应提示就完美了，比如进度条到100%后，显示正在转存，然后显示另外跳进度条那就很好了

我自己知道原因还好，但是我的站点开放了用户上传，用户不了解，这个问题的不便之处就会被放大很多

希望能把这个功能加上，体验会很好

**Comment by IvanChou** [comment]
~~解决是不可能解决的，这辈子都不可能去解决的，因为看上去要改很多东西，要加接口，要轮询~~

这个问题可以通过配合 OSS 的回源来处理，下一个版本会新增一个『关闭主动上传』的功能，到时候就冇问题了

**Comment by IvanChou** [comment]
『关闭主动上传』的功能已经上线，配合回源使用可解
