### ISSUE TITLE
后台「媒体库」中无内容

### ISSUE THREAD

**Issue by liliang13** [IvanChou/aliyun-oss-support#87]
因为转移到了新的服务器，通过导出导入对 wordpress 文章进行了备份和恢复，目前文章内链接正常，文章内图片显示正常。
导入前一直在正常使用插件，所有图片都在 OSS 上。
但是，转移到新服务器后发现，后台「媒体库」中，没有显示任何图片。
OSS 中图片都存在，缩略图也存在于 OSS 中。
我尝试了将 OSS 中的图片和缩略图全部上传至服务器对应目录下，后台「媒体库」中依然无内容。

![20190101145943](https://user-images.githubusercontent.com/1751239/50570874-7f373e00-0dd6-11e9-8388-c6f6b97737a9.png)上图是媒体库中无法显示图片的截图
![20190101150004](https://user-images.githubusercontent.com/1751239/50570875-7fcfd480-0dd6-11e9-8e73-498270ddf0b9.png)上图是插件配置的截图
![20190101150130](https://user-images.githubusercontent.com/1751239/50570876-7fcfd480-0dd6-11e9-9b40-5d1ff0a14a77.png)上图是本地服务器上的图片内容

**Comment by IvanChou** [comment]
sorry, 不知道那天脑子怎么糊住了，直接打了个 bug 的标签就跑了

正如 @tyt2y3 说的，WP 的导入导出并不会迁移附件的元数据，已经插入文章的附件因为是绝对地址，所以还是可以访问的，但 WP 已经没有把它们当做附件来管理了
