### ISSUE TITLE
启用插件后，媒体库中的url仍是本地url

### ISSUE THREAD

**Issue by Umiiii** [IvanChou/aliyun-oss-support#89]
wordpress version : 5.1.1
plugin version: 3.2.4
配置已经完成，插件开关也打开并关闭过了。
无论是在新版编辑器还是旧版编辑器，亦或是媒体库里面上传，url都仍然是本地的，图片也没传上oss，是什么问题呢？

**Comment by IvanChou** [comment]
插件根本没有工作，应该是有报错的，不过报错信息没有暴露出来

**Comment by Umiiii** [comment]
> 插件根本没有工作，应该是有报错的，不过报错信息没有暴露出来

有什么办法吗？

**Comment by IvanChou** [comment]
在 wp-config.php 中将 WP_DEBUG 设置为 true，再去后台关闭、开启插件，看有什么报错信息 😅

**Comment by IvanChou** [comment]
https://github.com/IvanChou/aliyun-oss-support/releases/tag/3.2.6
试用一下 3.2.6， 新增了异常处理，会抛出基本的错误信息

**Comment by Umiiii** [comment]
> https://github.com/IvanChou/aliyun-oss-support/releases/tag/3.2.6
> 试用一下 3.2.6， 新增了异常处理，会抛出基本的错误信息
> 
> 根据以往 issue 的经验，极有可能是你的 php 没有装 curl 扩展 #82

安装之后，确实显示
`阿里云 OSS: Extension {curl} is not installed or not enabled, please check your php env.`
我安装之后再试试
