### ISSUE TITLE
启用插件后，历史图片都无法显示了

### ISSUE THREAD

**Issue by yichen188** [IvanChou/aliyun-oss-support#90]
安装该插件之前，已经有添加了历史图片在媒体库中。
启用插件后，之前的图片都无法显示了，请问有什么办法可以解决？
谢谢。

**Comment by yichen188** [comment]
已经解决了
https://github.com/IvanChou/aliyun-oss-support/wiki/How-to-handle-old-images

**Comment by yichen188** [comment]
另一个问题，不知道与这个插件是否冲突？

允许 Jetpack 优化您的图片以提高页面加载速度，并通过我们的全球服务器网络提供您的图片和静态文件（例如，CSS 和 JavaScript）。

**Comment by IvanChou** [comment]
Jetpack 我没试过，你可以重新开一个 issue 来标记一下，不然我估计我会忘了

**Comment by yichen188** [comment]
也已经都解决了，是谷歌翻译的一个小工具拖慢了加载速度。
